name: Auto Posting
on:
  workflow_dispatch
  # push

jobs:
  PostTistory:
    runs-on: self-hosted
    steps:
    - name: "clone auto posting project"
      uses: actions/checkout@v4
      with:
        repository: YoungchoKim/AutoPosting
        ref: main
    - name: "cp config file"
      run: cp ${{CFG_FILE_PATH}} ./
    - name: "create virtual environments"
      run: python3 -m venv venv
    - name: "run venv"
      run: source venv/bin/activate
    - name: "install packages"
      run: python3 -m pip install -r requirements.txt
    - name: "run script"
      run: python3 sync_one_day.py
      
