name: Auto Posting

on:
  workflow_dispatch
  # push

jobs:
  PostTistory:
    runs-on: self-hosted
    steps:
    - name: "clone auto posting project"
      uses: actions/checkout@v4
      with:
        repository: YoungchoKim/AutoPosting
        ref: main
      env: 
        token: ${{ secrets.GIT_TOKEN }}
